### ISSUE TITLE
android.database.sqlite.SQLiteDatabaseCorruptException: file is encrypted or is not a database (Sqlite code 26), (OS error - 2:No such file or directory)

### ISSUE THREAD

**Issue by ramack** [ramack/ActivityDiary#175]
A user reported the following:

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
Caused by: android.database.sqlite.SQLiteDatabaseCorruptException: file is encrypted or is not a database (Sqlite code 26), (OS error - 2:No such file or directory)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:881)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:851)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
        at android.content.ContentResolver.query(ContentResolver.java:785)
        at android.content.ContentResolver.query(ContentResolver.java:716)
        at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:80)
        at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:61)
        at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:39)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more
android.database.sqlite.SQLiteDatabaseCorruptException: file is encrypted or is not a database (Sqlite code 26), (OS error - 2:No such file or directory)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:881)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:851)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
        at android.content.ContentResolver.query(ContentResolver.java:785)
        at android.content.ContentResolver.query(ContentResolver.java:716)
        at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:80)
        at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:61)
        at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:39)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
```

still unclear where it comes from and when it happens.

**Comment by ramack** [comment]
cannot reproduce, moved to 1.4.0 - if by then still not reproducible we'll close it.
