### ISSUE TITLE
UNIQUE constraint failed

### ISSUE THREAD

**Issue by ramack** [ramack/ActivityDiary#209]
Reported by Jan:
In case you tap very fast on the check for adding a new activity and want to add another one directly after the following exception occurs

```STACK_TRACE=android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: activity.name (code 2067)
#################################################################
Error Code : 2067 (SQLITE_CONSTRAINT_UNIQUE)
Caused By : Abort due to constraint violation.
	(UNIQUE constraint failed: activity.name (code 2067))
#################################################################
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:987)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:2007)
	at android.database.sqlite.SQLiteDatabase.insertOrThrow(SQLiteDatabase.java:1900)
	at de.rampro.activitydiary.db.ActivityDiaryContentProvider.insert(ActivityDiaryContentProvider.java:261)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:267)
	at android.content.ContentResolver.insert(ContentResolver.java:1545)
	at android.content.AsyncQueryHandler$WorkerHandler.handleMessage(AsyncQueryHandler.java:96)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by ramack** [comment]
it seems, that it is due to an activity with an empty name already existing and if you press the check before it could query the existing names and show the error message the activity is already closed and tries to safe the activity with empty name.
