### ISSUE TITLE
an NPE bug

### ISSUE THREAD

**Issue by tingsu** [ramack/ActivityDiary#261]
App version: 1.4.0
Platform: Android 6.0 emulator

STR:

1. fresh install the app and open the app
2. click 
![image](https://user-images.githubusercontent.com/3156978/51462709-47e7fb80-1d9c-11e9-9aa0-dcdc564a6758.png)
 on top

Exception Trace:

FATAL EXCEPTION: main
Process: de.rampro.activitydiary, PID: 6662
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String de.rampro.activitydiary.model.DiaryActivity.getName()' on a null object reference
	at de.rampro.activitydiary.ui.generic.EditActivity$QHandler$3.onClick(EditActivity.java:202)
	at android.view.View.performClick(View.java:5198)
	at android.view.View$PerformClick.run(View.java:21147)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ramack** [comment]
Thanks for the report. I have only quickly read at first, and as I saw you reporting for the Android Emulator, I did not put high priority on it, but I'll try to reproduce and take a closer look.

The main bug is in my eyes, that you seem to succeed to create two activities with the same name.

**Comment by tingsu** [comment]
Hi @ramack, thanks for providing this nice and handy app. Can I know will this issue be fixed soon?  It is a little wierd to be able to create two activities with same name.

**Comment by ramack** [comment]
The use case looks rather complicated, is that really so important for you? For sure it is a bug and it should be corrected, but it doesn't look critical to me. As I could not work for a long time on this app and some more important other issues are pending I don't want to promise anything here.
Except maybe that I will soon be more active here for this app!

**Comment by tingsu** [comment]
Thanks for your reply! I just feel it would be better to fix this issue. I provided a reproducing video to ease the inspection and make the use case more clear (not very complicated:). I totally understand you are quite busy with other things. I know maintaining an app need a lot of time and efforts. Never mind. Thanks!

**Comment by ramack** [comment]
your report is fully clear, I am just not confident that this happens very often, as most user won't create and delete an activity two times, but as said I agree that it should be fixed but probably more later than sooner :-)
