### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal pattern character in DateFormat string

### ISSUE THREAD

**Issue by ramack** [ramack/ActivityDiary#279]
```
STACK_TRACE=java.lang.IllegalArgumentException: Illegal pattern character 'n'
	at java.text.SimpleDateFormat.compile(SimpleDateFormat.java:873)
	at java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:687)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:658)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:633)
	at de.rampro.activitydiary.helpers.DateHelper.dateFormat(DateHelper.java:85)
	at de.rampro.activitydiary.ui.statistics.StatisticsActivity.loadRange(StatisticsActivity.java:295)
	at de.rampro.activitydiary.ui.statistics.StatisticsActivity.onItemSelected(StatisticsActivity.java:264)
	at android.widget.AdapterView.fireOnSelected(AdapterView.java:947)
	at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:936)
	at android.widget.AdapterView.access$300(AdapterView.java:56)
	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:901)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by ramack** [comment]
this depends on the locale. Fixed it for Espaniol today. So closing it until reported for another langauge.
