### ISSUE TITLE
Crash on Camera, Note Edit and Settings

### ISSUE THREAD

**Issue by ramack** [ramack/ActivityDiary#60]
Report on [f-droid inclusion MR](https://gitlab.com/fdroid/fdroiddata/merge_requests/2633), by relan:

- [x] I started the app (on a tablet with Android 7.1.2), pressed Camera button and it immediately crashed with:
12-10 09:48:46.707 28777 28777 E AndroidRuntime: Process: de.rampro.activitydiary, PID: 28777
12-10 09:48:46.707 28777 28777 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
12-10 09:48:46.707 28777 28777 E AndroidRuntime:    at de.rampro.activitydiary.ui.main.j.onClick(Unknown Source)
12-10 09:48:46.707 28777 28777 E AndroidRuntime:    at android.view.View.performClick(View.java:5637)
12-10 09:48:46.707 28777 28777 E AndroidRuntime:    at android.view.View$PerformClick.run(View.java:22429)
12-10 09:48:46.707 28777 28777 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:751)
12-10 09:48:46.707 28777 28777 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:95)
12-10 09:48:46.707 28777 28777 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:154)
12-10 09:48:46.707 28777 28777 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6121)
12-10 09:48:46.707 28777 28777 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
12-10 09:48:46.707 28777 28777 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-10 09:48:46.707 28777 28777 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

- [x] When I pressed Edit button (with a pencil icon) and then OK in the dialog, it crashed with:
12-10 09:52:51.474 29351 29375 E AndroidRuntime: FATAL EXCEPTION: AsyncQueryWorker
12-10 09:52:51.474 29351 29375 E AndroidRuntime: Process: de.rampro.activitydiary, PID: 29351
12-10 09:52:51.474 29351 29375 E AndroidRuntime: java.lang.NullPointerException: uri
12-10 09:52:51.474 29351 29375 E AndroidRuntime:    at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:111)
12-10 09:52:51.474 29351 29375 E AndroidRuntime:    at android.content.ContentResolver.update(ContentResolver.java:1402)
12-10 09:52:51.474 29351 29375 E AndroidRuntime:    at android.content.AsyncQueryHandler$WorkerHandler.handleMessage(AsyncQueryHandler.java:100)
12-10 09:52:51.474 29351 29375 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
12-10 09:52:51.474 29351 29375 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:154)
12-10 09:52:51.474 29351 29375 E AndroidRuntime:    at android.os.HandlerThread.run(HandlerThread.java:61)

- [ ] Settings also cause a crash. I think your app isn't ready for inclusion yet.

**Comment by ramack** [comment]
This is related to the fact, that no activity was selected before. We should ask for an activity first...

**Comment by ramack** [comment]
the settings crash I cannot reproduce though
