### ISSUE TITLE
Not all Cursors are correctly closes

### ISSUE THREAD

**Issue by ramack** [ramack/ActivityDiary#62]
12-10 00:55:50.987: W/AsyncQuery(11166): android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=959 (# cursors opened by this proc=959)
12-10 00:55:50.987: W/AsyncQuery(11166): 	at android.database.CursorWindow.<init>(CursorWindow.java:108)
12-10 00:55:50.987: W/AsyncQuery(11166): 	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
From time to time this happens:

12-10 00:55:50.987: W/AsyncQuery(11166): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
12-10 00:55:50.987: W/AsyncQuery(11166): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
12-10 00:55:50.987: W/AsyncQuery(11166): 	at android.content.ContentResolver.query(ContentResolver.java:773)
12-10 00:55:50.987: W/AsyncQuery(11166): 	at android.content.ContentResolver.query(ContentResolver.java:704)
12-10 00:55:50.987: W/AsyncQuery(11166): 	at android.content.ContentResolver.query(ContentResolver.java:662)
12-10 00:55:50.987: W/AsyncQuery(11166): 	at android.content.AsyncQueryHandler$WorkerHandler.handleMessage(AsyncQueryHandler.java:79)
12-10 00:55:50.987: W/AsyncQuery(11166): 	at android.os.Handler.dispatchMessage(Handler.java:105)
12-10 00:55:50.987: W/AsyncQuery(11166): 	at android.os.Looper.loop(Looper.java:164)
12-10 00:55:50.987: W/AsyncQuery(11166): 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-10 00:55:50.989: E/CursorWindow(11166): Could not allocate CursorWindow '/data/user/0/de.rampro.activitydiary/databases/de.rampro.activitydiary.provider' of size 2097152 due to error -24.

and this seems to be due to non correctly closed cursors...

**Comment by ramack** [comment]
see 8d80e0fd8334163fd2a1cfb4379f4e8be0e93446
