### ISSUE TITLE
RecyclerView notifications

### ISSUE THREAD

**Issue by ramack** [ramack/ActivityDiary#65]
... are not clean right now and need to be perfectly consistent:
insert on add, remove on delete, etc.
Shall be only based on the Conentprovider and its change notifications.
in MainActivity the handlers shall not be unregistered on activity hide.

**Comment by ramack** [comment]
This seem to be related to the crash reports showing a stack trace like that
```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 9(offset:10).state:10 android.support.v7.widget.RecyclerView{f2c4da8 VFEDH.... ......ID 0,270-540,840 #7f0900bc app:id/select_recycler}, adapter:de.rampro.activitydiary.ui.main.SelectRecyclerViewAdapter@d7670c1, layout:android.support.v7.widget.StaggeredGridLayoutManager@80f0066, context:de.rampro.activitydiary.ui.main.MainActivity@ebe0ec8
at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5628)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
at android.support.v7.widget.LayoutState.next(LayoutState.java:100)
at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1570)
at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:682)
at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:604)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3644)
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3408)
at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
```

**Comment by ramack** [comment]
also those look similar
```
java.lang.IndexOutOfBoundsException: 
 
  at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition (RecyclerView.java:5421)
 
  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline (RecyclerView.java:5603)
 
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition (RecyclerView.java:5563)
 
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition (RecyclerView.java:5559)
 
  at android.support.v7.widget.LayoutState.next (LayoutState.java:100)
 
  at android.support.v7.widget.StaggeredGridLayoutManager.fill (StaggeredGridLayoutManager.java:1570)
 
  at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren (StaggeredGridLayoutManager.java:682)
 
  at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren (StaggeredGridLayoutManager.java:604)
```

**Comment by ramack** [comment]
USER_COMMENT=no spaces in activity name allowed?
```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{dd96da1 position=10 id=-1, oldPos=9, pLpos:9 scrap [attachedScrap] tmpDetached not recyclable(1) no parent} android.support.v7.widget.RecyclerView{f853f9 VFEDH.... ......ID 0,630-1080,1640 #7f0900bc app:id/select_recycler}, adapter:de.rampro.activitydiary.ui.main.SelectRecyclerViewAdapter@ee7cf3e, layout:android.support.v7.widget.StaggeredGridLayoutManager@1cc519f, context:de.rampro.activitydiary.ui.main.MainActivity@f123b70
        at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5421)
        at 
```

**Comment by ramack** [comment]
Problem is right now, that we have a mix of specific notification calls like
selectAdapter.notifyItemInserted

but also selectRecyclerView.swapAdapter is called due to onActivityOrderChanged after a likelyhood change...
