### ISSUE TITLE
Deleting Images in the history Crashes

### ISSUE THREAD

**Issue by ramack** [ramack/ActivityDiary#69]
```
java.lang.IllegalStateException: idRowIdx not valid
at de.rampro.activitydiary.ui.generic.DetailRecyclerViewAdapter.getDiaryImageIdAt(DetailRecyclerViewAdapter.java:154)
at de.rampro.activitydiary.ui.history.HistoryRecyclerViewAdapter$1.onClick(HistoryRecyclerViewAdapter.java:86)
at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
at android.os.Handler.dispatchMessage(Handler.java:102)
```

at first sight it looks like a mess up adapterPosition in the innter and outer adapters in `mViewHolders.get(adapterPosition).mDetailAdapter.getDiaryImageIdAt(adapterPosition))`

=> it would be the time to care about
//TODO: generalize the DetailView to include this code also

**Comment by ramack** [comment]
this is fixed by 9dc15773bc1d3ac563602887f43816f08650d308
