### ISSUE TITLE
Cursors not closed correctly

### ISSUE THREAD

**Issue by ramack** [ramack/ActivityDiary#78]
```
02-09 21:21:01.611 19198-19213/? W/AsyncQuery: Exception thrown during handling EVENT_ARG_QUERY
                                               android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 2062)
                                               #################################################################
                                               Error Code : 2062 (SQLITE_CANTOPEN_EMFILE)
                                               Caused By : Application has opened two many files. Maximum of available file descriptors in one process is 1024 in default.
                                               	(unable to open database file (code 2062))
                                               #################################################################
                                                   at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
                                                   at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:930)
                                                   at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
                                                   at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
                                                   at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
                                                   at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
                                                   at android.content.ContentResolver.query(ContentResolver.java:555)
                                                   at android.content.ContentResolver.query(ContentResolver.java:478)
```

**Comment by ramack** [comment]
G prelaunch report is green now. so 22da843 fixis #78.
